name: API heroku deployment - Feature Pull Request

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - api/**

jobs:
  build:
    env:
      APP_NAME: ''
      BRANCH_NAME: ''
      DB_URI: ''
      HEROKU_API_KEY: cd71ad0d-c73b-403b-b917-1ed8c5c3dfa1
      PR_ID: ''

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get BRANCH_NAME
        run: echo "::set-env name=BRANCH_NAME::$(echo $GITHUB_HEAD_REF |  tr / -)"

      - name: Get PR_ID
        run: sudo apt-get install jq && echo "::set-env name=PR_ID::$(cat $GITHUB_EVENT_PATH | jq -r '.number')"

      - name: Set APP_NAME
        run: echo "::set-env name=APP_NAME::df-spectrum-pr-${{ env.PR_ID }}"

      - name: Create Heroku app
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: apps:create -a ${{ env.APP_NAME }}
        continue-on-error: true

      - name: Set Heroku app env
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: config:set MONGO_URI=${{ secrets.DB_URI }}/db-pr${{ env.PR_ID }} YARN_PRODUCTION=false -a ${{ env.APP_NAME }}

      - name: Heroku login
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:login
      - name: Heroku push
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:push -a ${{ env.APP_NAME }} web
      - name: Heroku release
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: container:release -a ${{ env.APP_NAME }} web

      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({...context.issue, body: '[[${{ env.APP_NAME }}] Preview Deploy for branch ${{ env.BRANCH_NAME }}](https://df-spectrum-pr-${{ env.PR_ID }}.herokuapp.com/graphql)'})
