name: API heroku remove app - Merge Pull Request

on:
  pull_request:
    types: ['closed']
    paths:
      - api/**

jobs:
  build:
    env:
      APP_NAME: ''
      BRANCH_NAME: ''
      PR_ID: ''

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get BRANCH_NAME
        run: echo "::set-env name=BRANCH_NAME::$(echo $GITHUB_HEAD_REF |  tr / -)"

      - name: Get PR_ID
        run: sudo apt-get install jq && echo "::set-env name=PR_ID::$(cat $GITHUB_EVENT_PATH | jq -r '.number')"

      - name: Set APP_NAME
        run: echo "::set-env name=APP_NAME::df-spectrum-pr-${{ env.PR_ID }}"

      - name: Remove Heroku app
        uses: actions/heroku@master
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        with:
          args: apps:destroy -a ${{ env.APP_NAME }} --confirm=${{ env.APP_NAME }}
