name: Client NOW deployment - Master push

on:
  push:
    branches:
      - master
    paths:
      - client/**
      - now.json
      - '!client/.storybook/**'
      - '!**.stories.tsx'
      - '!**.stories.js'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: amondnet/now-deployment@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          zeit-token: ${{ secrets.ZEIT_NOW_TOKEN }}
          now-args: '--prod --force'
