name: Storybook netlify deployment - Feature Pull Request - Sync

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - client/.storybook/**
      - '**.stories.tsx'
      - '**.stories.js'

jobs:
  build:
    env:
      APP_NAME: 'Storybook'
      DEPLOY_PREVIEW_URL: ''
      BRANCH_NAME: ''

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Get BRANCH_NAME
        run: |
          echo "::set-env name=BRANCH_NAME::$(echo $GITHUB_HEAD_REF |  tr / -)"

      - name: Install dependencies
        run: |
          yarn

      - name: Netlify Storybook deployment
        env:
          NETLIFY_SITE_ID: ${{ secrets.STORYBOOK_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          yarn build-storybook
          echo "::set-env name=DEPLOY_PREVIEW_URL::$(npx netlify-cli deploy --dir=client/storybook-static --message='Pull Request $GITHUB_HEAD_REF'| grep "Live Draft URL" |  grep -o -E 'https?://[^ ]+' )"

      - uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({...context.issue, body: '[[${{ env.APP_NAME }}] Preview Deploy for branch ${{ env.BRANCH_NAME }}](${{env.DEPLOY_PREVIEW_URL}})'})
